#pragma once
enum ControllableEvent
{
    PRESSED_UP,
    PRESSED_DOWN,
    PRESSED_LEFT,
    PRESSED_RIGHT,
    PRESSED_ACTION1,
	PRESSED_PAUSE,
    RELEASED_UP,
    RELEASED_DOWN,
    RELEASED_LEFT,
    RELEASED_RIGHT,
    RELEASED_ACTION1,
	RELEASED_PAUSE
};