#pragma once
enum InputEvent{
  PRESSED_UP,
  PRESSED_DOWN,
  PRESSED_LEFT,
  PRESSED_RIGHT,
  PRESSED_A,
  PRESSED_B,
  PRESSED_START,
  PRESSED_PAUSE,
  RELEASED_UP,
  RELEASED_DOWN,
  RELEASED_LEFT,
  RELEASED_RIGHT,
  RELEASED_A,
  RELEASED_B,
  RELEASED_START,
  RELEASED_PAUSE
};